### ISSUE TITLE
Error while initializing project

### ISSUE THREAD

**Issue by bugude** [coolgk/project-templates#10]
Facing below error while running "npx create-typescript-express-app <folder>".

`events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'init', '-y' ]
}
`

**Comment by coolgk** [comment]
hello, can you please share node, npm and os versions? there are some known issues for old node versions (<10)

**Comment by bugude** [comment]
> hello, can you please share node, npm and os versions? there are some known issues for old node versions (<10)

$ npm --version
6.14.5

$ node --version
v12.18.2

OS is Windows 10 and on the latest patch

**Comment by coolgk** [comment]
@bugude thanks for the info. please try  `npx create-typescript-express-app test-app` again. You might need to install dev dependencies globally in Windows. It's better to run node in WSL https://docs.microsoft.com/en-gb/windows/wsl/install-win10
