### ISSUE TITLE
Fails creating directories

### ISSUE THREAD

**Issue by AllanCochrane** [coolgk/project-templates#5]
cd /tmp
➜  /tmp npx create-node-typescript-app blah
npx: installed 1 in 2.042s
Initialising Project

(node:29198) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '/private/tmp/blah/tests/src'
    at Object.fs.mkdirSync (fs.js:885:18)
    at subDirectories.forEach (/Users/allancochrane/.npm/_npx/29198/lib/node_modules/create-node-typescript-app/dist/src/bin/startNodeTypescriptApp.js:20:22)
    at Array.forEach (<anonymous>)
    at createProjectDirectory (/Users/allancochrane/.npm/_npx/29198/lib/node_modules/create-node-typescript-app/dist/src/bin/startNodeTypescriptApp.js:19:20)
    at Object.startNodeTypescriptApp [as default] (/Users/allancochrane/.npm/_npx/29198/lib/node_modules/create-node-typescript-app/dist/src/bin/startNodeTypescriptApp.js:80:30)
    at Object.<anonymous> (/Users/allancochrane/.npm/_npx/29198/lib/node_modules/create-node-typescript-app/bin/cli:3:58)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
(node:29198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
➜  /tmp npm -v
6.4.1

**Comment by coolgk** [comment]
hey sorry, somehow I didn't get a notification for this. is this still happening? OS and node version, please?

**Comment by AllanCochrane** [comment]
OS: MacOS Catalina

➜  /tmp node -v
v8.15.1
➜  /tmp npm -v
6.4.1
➜  /tmp

**Comment by coolgk** [comment]
@AllanCochrane  thanks for the update. I tried to make it work with node 8, the `npx` command works now but it doesn't seem to be a quick job to fix rest of the configurations, please upgrade to node 10+ (https://github.com/nvm-sh/nvm). The latest lts is 12 or you can try to adjust the `tsconfig.json` to transpile the code to es5

If you plan to create an express app, you can also use this package https://www.npmjs.com/package/create-typescript-express-app (also requires node 10+)
